### PR TITLE
Fix MD002 First header should be a top level header

### PR DESCRIPTION
**Pull request by ericherman**
I think we will wish to word-smith on the top-level headings, but I'd like to do that after we have the structure in place.

Looking at the render, we may wish to investigate different styling for the sub-phases, but that's also not part of this patch.

-----
[View rendered _phases/01.md](https://github.com/publiccodenet/process-code-software-procurement/blob/fix-MD002/_phases/01.md)
[View rendered _phases/02.md](https://github.com/publiccodenet/process-code-software-procurement/blob/fix-MD002/_phases/02.md)
[View rendered _phases/03.md](https://github.com/publiccodenet/process-code-software-procurement/blob/fix-MD002/_phases/03.md)
[View rendered _phases/04.md](https://github.com/publiccodenet/process-code-software-procurement/blob/fix-MD002/_phases/04.md)
[View rendered _phases/05.md](https://github.com/publiccodenet/process-code-software-procurement/blob/fix-MD002/_phases/05.md)
[View rendered _phases/06.md](https://github.com/publiccodenet/process-code-software-procurement/blob/fix-MD002/_phases/06.md)
[View rendered _phases/07.md](https://github.com/publiccodenet/process-code-software-procurement/blob/fix-MD002/_phases/07.md)
[View rendered _phases/08.md](https://github.com/publiccodenet/process-code-software-procurement/blob/fix-MD002/_phases/08.md)
[View rendered _phases/09.md](https://github.com/publiccodenet/process-code-software-procurement/blob/fix-MD002/_phases/09.md)
[View rendered _phases/10.md](https://github.com/publiccodenet/process-code-software-procurement/blob/fix-MD002/_phases/10.md)
[View rendered _phases/11.md](https://github.com/publiccodenet/process-code-software-procurement/blob/fix-MD002/_phases/11.md)
[View rendered _phases/12.md](https://github.com/publiccodenet/process-code-software-procurement/blob/fix-MD002/_phases/12.md)
[View rendered _phases/13.md](https://github.com/publiccodenet/process-code-software-procurement/blob/fix-MD002/_phases/13.md)

### CODE REVIEW

**Comment by Ainali** [comment]
Hm, since the pages for phases gets included in the index page, it will yield several h1 on one page, and I don't think we want that. I think those should not be seen as "pages" but as components.

**Comment by ericherman** [comment]
> Hm, since the pages for phases gets included in the index page, it will yield several h1 on one page, and I don't think we want that. I think those should not be seen as "pages" but as components.

I was thinking of this in terms of CSS styling, wanting to have them as separate pages or components is layout.

However, if they will always be included as components, and the components used in only one place, should we in-line them?

**Comment by ericherman** [comment]
I'm starting to experience some "sheer" between the markdown and the HTML created by my understanding of the assumptions of the markdown-generating-html and linter .... Is the conceptual model of the generation to assume a simplicity that this component form breaks?

We can, for now, simply accept this linting exception; if we do so, I'd suggest that we comment this more clearly in each "component" page.

Perhaps is this something that can be addressed by adding information to the front-matter?

**Comment by Ainali** [comment]
> However, if they will always be included as components, and the components used in only one place, should we in-line them?

We could do that, but I think that the navigation bar relies on these and that we'll have to redo that one if we include all the pages.

**Comment by ericherman** [comment]
Fighting against tools is never fun, let's zoom out a bit and examine what we want and what is easily supported.

Let's close this for now, and when we know a bit more about the generator and how to do "component page" inclusion, let's return to it.

Commenting in the "component pages" that the pages are not expected to have a normal form starting with a top-level header would be a very good thing to add; that is a different patch.

**Pull request closed without merging**
