### PR TITLE
Fix MD034 bare URL errors

### PR DESCRIPTION
**Pull request by ericherman**
null

-----
[View rendered _phases/02.md](https://github.com/publiccodenet/process-code/blob/fix-MD034/_phases/02.md)
[View rendered _phases/03.md](https://github.com/publiccodenet/process-code/blob/fix-MD034/_phases/03.md)
[View rendered _phases/04.md](https://github.com/publiccodenet/process-code/blob/fix-MD034/_phases/04.md)
[View rendered _phases/05.md](https://github.com/publiccodenet/process-code/blob/fix-MD034/_phases/05.md)

### CODE REVIEW

**Review by Ainali — CHANGES_REQUESTED** [review]
The references to 18F are different in 02.md, 03.md and 05.md. We should pick one style for all of them. (I like the one in 02.md best)

**Comment by ericherman** [comment]
I do not love the text for the links, but I think it is okay for getting the structure in place, and we can "wordsmith" on it in the coming days.

**Comment by ericherman** [comment]
> The references to 18F are different in 02.md, 03.md and 05.md. We should pick one style for all of them. (I like the one in 02.md best)

Ah, yes. I can do that tomorrow.

**Review by Ainali — APPROVED** [review]

**Comment by Ainali** [comment]
Good catch on the Citymart!

**Pull request merged**
